spring.application.name=CNTT2_IT211_Project



#Config Datasource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hr_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123


#Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Config Token
jwt-secret=abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
# 15 phút
jwt-expired=900
# 7 ngày
jwt-refresh-expired=604800


#Config file lên Cloudinary
cloudinary.cloud-name=deyuvrsv9
cloudinary.api-key=294582536614528
cloudinary.api-secret=z43Jx3bzpyBQjijteSB9RzLO8cU


#Config Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


#Config logging
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss.SSS} -  %highlight(%-5level) - %cyan(%logger{50}) - %green(%msg%n)
logging.logback.rollingpolicy.max-file-size=20MB
logging.logback.rollingpolicy.max-history=30
logging.level.root=INFO
logging.level.com.re = INFO